import { defineConfig } from 'vitepress'
import dynamicSidebar from './sidebar'

// Build complete zh sidebar by merging static entries with dynamic ones.
// Dynamic entries come from sidebar.ts (auto-generated by scripts/generate_docs_index.py).
const zhSidebar = Object.assign(
  {
    '/zh/eu_mdr/': [
      { text: 'EU MDR 概述', link: '/zh/eu_mdr/' },
      {
        text: '法规文本', link: '/zh/eu_mdr/regulations',
        collapsed: true,
        items: [
          { text: '第10条 — 制造商一般义务', link: '/zh/eu_mdr/regulations/art-10-manufacturer-obligations' },
          { text: '第52条 — 合规评估程序', link: '/zh/eu_mdr/regulations/art-52-conformity-assessment' },
          { text: '附件I — GSPR', link: '/zh/eu_mdr/regulations/annex-i-gspr' },
          { text: '附件II — 技术文件', link: '/zh/eu_mdr/regulations/annex-ii-technical-documentation' },
          { text: '附件III — PMS技术文件', link: '/zh/eu_mdr/regulations/annex-iii-pms' },
          { text: '附件XIV — 临床评价', link: '/zh/eu_mdr/regulations/annex-xiv-clinical-evaluation' },
        ],
      },
      {
        text: '协调标准', link: '/zh/eu_mdr/standards',
        collapsed: true,
        items: [
          { text: '质量管理', link: '/zh/eu_mdr/standards/quality-management' },
          { text: '风险管理', link: '/zh/eu_mdr/standards/risk-management' },
          { text: '生物相容性', link: '/zh/eu_mdr/standards/biocompatibility' },
          { text: '电气安全与EMC', link: '/zh/eu_mdr/standards/electrical-safety' },
          { text: '灭菌与包装', link: '/zh/eu_mdr/standards/sterilization' },
          { text: '软件与可用性', link: '/zh/eu_mdr/standards/software' },
          { text: '标签与说明书', link: '/zh/eu_mdr/standards/labelling' },
          { text: '临床评价与临床调查', link: '/zh/eu_mdr/standards/clinical-investigation' },
          { text: '非有源外科植入物', link: '/zh/eu_mdr/standards/surgical-implants' },
          { text: '医用手套', link: '/zh/eu_mdr/standards/medical-gloves' },
          { text: '手术衣物与口罩', link: '/zh/eu_mdr/standards/surgical-textiles' },
          { text: '患者搬运设备', link: '/zh/eu_mdr/standards/patient-handling' },
          { text: '器械处理与再处理', link: '/zh/eu_mdr/standards/processing' },
          { text: '小口径连接器', link: '/zh/eu_mdr/standards/connectors' },
        ],
      },
      { text: 'MDCG 指南', link: '/zh/eu_mdr/mdcg' },
      { text: 'TEAM-NB 立场文件', link: '/zh/eu_mdr/team_nb' },
    ],
    '/zh/fda/': [
      { text: 'FDA 概述', link: '/zh/fda/' },
      { text: '法规 (21 CFR)', link: '/zh/fda/regulations' },
      { text: '共识标准', link: '/zh/fda/standards' },
      { text: '指南文件', link: '/zh/fda/guidance' },
    ],
    '/zh/nmpa/': [
      { text: 'NMPA 概述', link: '/zh/nmpa/' },
      { text: '法规规章', link: '/zh/nmpa/regulations' },
      { text: 'GB/YY 标准', link: '/zh/nmpa/standards' },
      { text: '指导原则', link: '/zh/nmpa/guidance' },
      { text: '分类目录', link: '/zh/nmpa/classification' },
    ],
    '/zh/shared/': [
      { text: '通用标准', link: '/zh/shared/standards' },
    ],
  },
  dynamicSidebar,
)

export default defineConfig({
  title: 'DocMCP Knowledge Base',
  description: 'Open regulatory knowledge base for medical device compliance',
  srcDir: '.',
  ignoreDeadLinks: true,

  locales: {
    root: {
      label: 'English',
      lang: 'en',
      link: '/en/',
      themeConfig: {
        nav: [
          { text: 'Home', link: '/' },
          { text: 'EU MDR', link: '/en/eu_mdr/' },
          { text: 'FDA', link: '/en/fda/' },
          { text: 'NMPA', link: '/en/nmpa/' },
          { text: 'Standards', link: '/en/shared/standards' },
          { text: 'Insights', link: '/en/insights/' },
        ],
        sidebar: {
          '/en/eu_mdr/': [
            { text: 'EU MDR Overview', link: '/en/eu_mdr/' },
            { text: 'Regulations', link: '/en/eu_mdr/regulations' },
            { text: 'Harmonised Standards', link: '/en/eu_mdr/standards' },
            { text: 'MDCG Guidance', link: '/en/eu_mdr/mdcg' },
            { text: 'TEAM-NB Position Papers', link: '/en/eu_mdr/team_nb' },
          ],
          '/en/fda/': [
            { text: 'FDA Overview', link: '/en/fda/' },
            { text: 'Regulations (21 CFR)', link: '/en/fda/regulations' },
            { text: 'Consensus Standards', link: '/en/fda/standards' },
            { text: 'Guidance Documents', link: '/en/fda/guidance' },
          ],
          '/en/nmpa/': [
            { text: 'NMPA Overview', link: '/en/nmpa/' },
            { text: 'Regulations', link: '/en/nmpa/regulations' },
            { text: 'GB/YY Standards', link: '/en/nmpa/standards' },
            { text: 'Guidance Principles', link: '/en/nmpa/guidance' },
            { text: 'Classification', link: '/en/nmpa/classification' },
          ],
          '/en/insights/': [
            { text: 'Insights Home', link: '/en/insights/' },
            { text: 'Regulatory Analysis', link: '/en/insights/analysis' },
            { text: 'NMPA Updates', link: '/en/insights/nmpa-updates' },
            { text: 'EU MDR Updates', link: '/en/insights/eu-mdr-updates' },
            { text: 'FDA Updates', link: '/en/insights/fda-updates' },
          ],
        },
        socialLinks: [
          { icon: 'github', link: 'https://github.com/RASAAS/docmcp-knowledge' }
        ],
        footer: {
          message: 'Content licensed under CC BY 4.0',
          copyright: 'Copyright © 2026 RASAAS'
        },
        search: { provider: 'local' }
      }
    },
    zh: {
      label: '中文',
      lang: 'zh-CN',
      link: '/zh/',
      themeConfig: {
        nav: [
          { text: '首页', link: '/zh/' },
          { text: 'EU MDR', link: '/zh/eu_mdr/' },
          { text: 'FDA', link: '/zh/fda/' },
          { text: 'NMPA', link: '/zh/nmpa/' },
          { text: '标准', link: '/zh/shared/standards' },
          { text: '法规解读', link: '/zh/insights/' },
        ],
        sidebar: zhSidebar,
        socialLinks: [
          { icon: 'github', link: 'https://github.com/RASAAS/docmcp-knowledge' }
        ],
        footer: {
          message: '内容以 CC BY 4.0 许可证授权',
          copyright: 'Copyright © 2026 RASAAS'
        },
        search: { provider: 'local' }
      }
    }
  },

  themeConfig: {
    logo: { light: '/logo.png', dark: '/logo-dark.png', alt: 'DocMCP' },
  }
})
