// Auto-generated by scripts/generate_docs_index.py — DO NOT EDIT
export default {
  "/en/insights/": [
    {
      "text": "Regulatory Insights",
      "link": "/en/insights/"
    },
    {
      "text": "NMPA Updates (8)",
      "collapsed": true,
      "items": [
        {
          "text": "View in Chinese (8 articles)",
          "link": "/zh/insights/nmpa-updates"
        }
      ]
    },
    {
      "text": "EU MDR Updates (15)",
      "collapsed": true,
      "items": [
        {
          "text": "View in Chinese (15 articles)",
          "link": "/zh/insights/eu-mdr-updates"
        }
      ]
    },
    {
      "text": "FDA Updates (4)",
      "collapsed": true,
      "items": [
        {
          "text": "View in Chinese (4 articles)",
          "link": "/zh/insights/fda-updates"
        }
      ]
    },
    {
      "text": "Regulatory Analysis (26)",
      "collapsed": true,
      "items": [
        {
          "text": "View in Chinese (26 articles)",
          "link": "/zh/insights/analysis"
        }
      ]
    },
    {
      "text": "Clinical Evaluation (21)",
      "collapsed": true,
      "items": [
        {
          "text": "Clinical Evaluation Scope",
          "link": "/en/insights/clinical-evaluation/临床评价范围"
        },
        {
          "text": "Benchmark or Similar Devices",
          "link": "/en/insights/clinical-evaluation/benchmark-and-similar-device"
        },
        {
          "text": "Clinical Development Plan (CDP)",
          "link": "/en/insights/clinical-evaluation/cdp"
        },
        {
          "text": "Clinical Evaluation Report (CER)",
          "link": "/en/insights/clinical-evaluation/cer"
        },
        {
          "text": "Clinical Evaluation Services",
          "link": "/en/insights/clinical-evaluation/clincial-evaluation-services"
        },
        {
          "text": "Clinical Data Analysis",
          "link": "/en/insights/clinical-evaluation/clinical-data-analysis"
        },
        {
          "text": "Data Appraisal and Analysis",
          "link": "/en/insights/clinical-evaluation/data-appraisal-and-analysis"
        },
        {
          "text": "Data Generated by the Manufacturer",
          "link": "/en/insights/clinical-evaluation/data-generated-by-the-manufacturer"
        },
        {
          "text": "Data Collection Report (DCR)",
          "link": "/en/insights/clinical-evaluation/dcr"
        },
        {
          "text": "EndNote Import and Export",
          "link": "/en/insights/clinical-evaluation/endnote-import-export"
        },
        {
          "text": "Equivalent Device",
          "link": "/en/insights/clinical-evaluation/equivalency"
        },
        {
          "text": "Literature Databases and Justification",
          "link": "/en/insights/clinical-evaluation/lit-database"
        },
        {
          "text": "Literature Appraisal Criteria",
          "link": "/en/insights/clinical-evaluation/lit-review-standard"
        },
        {
          "text": "Literature Search Protocol (LSP)",
          "link": "/en/insights/clinical-evaluation/lsp"
        },
        {
          "text": "MDCG 2025-9 Guidance: Breakthrough Devices (BtX)",
          "link": "/en/insights/clinical-evaluation/mdcg-2025-9"
        },
        {
          "text": "Objectives, Inputs and Device Under Evaluation",
          "link": "/en/insights/clinical-evaluation/objective-input-due"
        },
        {
          "text": "Risk Management in Clinical Evaluation",
          "link": "/en/insights/clinical-evaluation/risk-management"
        },
        {
          "text": "Literature Screening Criteria",
          "link": "/en/insights/clinical-evaluation/screening-criteria"
        },
        {
          "text": "Literature Screening Process",
          "link": "/en/insights/clinical-evaluation/screening-process"
        },
        {
          "text": "Literature Search Strategy",
          "link": "/en/insights/clinical-evaluation/search-strategy"
        },
        {
          "text": "Clinical Background (State of the Art)",
          "link": "/en/insights/clinical-evaluation/sota"
        }
      ]
    }
  ]
}
