// Auto-generated by scripts/generate_docs_index.py — DO NOT EDIT
export default {
  "/zh/insights/": [
    {
      "text": "法规解读",
      "link": "/zh/insights/"
    },
    {
      "text": "NMPA 合规动态 (8)",
      "collapsed": true,
      "items": [
        {
          "text": "NMPA合规信息更新：2024.07-2024.09",
          "link": "/zh/insights/nmpa-updates/2407-2409"
        },
        {
          "text": "NMPA合规信息更新：2024.10 - 2024.12",
          "link": "/zh/insights/nmpa-updates/2410-2412"
        },
        {
          "text": "NMPA合规信息更新：2025.01 - 2025.03",
          "link": "/zh/insights/nmpa-updates/2501-2503"
        },
        {
          "text": "NMPA合规信息更新：2025.04 – 2025.06",
          "link": "/zh/insights/nmpa-updates/2504-2506"
        },
        {
          "text": "NMPA合规信息更新：2025.07 – 2025.09",
          "link": "/zh/insights/nmpa-updates/2507-2509"
        },
        {
          "text": "NMPA合规信息更新：2025.10 – 2025.12",
          "link": "/zh/insights/nmpa-updates/2510-2512"
        },
        {
          "text": "MDR合规深度解析：按照各国语言要求优化欧洲市场准入",
          "link": "/zh/insights/nmpa-updates/mdr-language-requirements"
        },
        {
          "text": "国务院关于修改和废止部分行政法规的决定",
          "link": "/zh/insights/nmpa-updates/state-council-order-797"
        }
      ]
    },
    {
      "text": "EU MDR 合规动态 (15)",
      "collapsed": true,
      "items": [
        {
          "text": "欧盟AI法案对医疗器械的影响：合规路线图与实施策略解析",
          "link": "/zh/insights/eu-mdr-updates/ai-act-compliance"
        },
        {
          "text": "临床试验报告管理新规解读：EUDAMED缺位下的合规路径",
          "link": "/zh/insights/eu-mdr-updates/cir-requirements"
        },
        {
          "text": "EU MDR 分类",
          "link": "/zh/insights/eu-mdr-updates/classification"
        },
        {
          "text": "EU IVDR 分类",
          "link": "/zh/insights/eu-mdr-updates/eu-ivdr-classification"
        },
        {
          "text": "EU MDR Classification Explanations",
          "link": "/zh/insights/eu-mdr-updates/eu-mdr-classification-explanations"
        },
        {
          "text": "欧盟医疗器械监管新框架解析：网络安全与责任制度的多维革新",
          "link": "/zh/insights/eu-mdr-updates/eu-mdr-cybersecurity"
        },
        {
          "text": "EUDAMED数据库分阶段实施政策重要更新解读",
          "link": "/zh/insights/eu-mdr-updates/eudamed-implementation-phases"
        },
        {
          "text": "官方指南：EUDAMED UDI/器械模块操作详解",
          "link": "/zh/insights/eu-mdr-updates/eudamed-udi-user-guide-v3110"
        },
        {
          "text": "IVDR 分类规则与实例汇总 (基于 MDCG 2020-16 Rev.4)",
          "link": "/zh/insights/eu-mdr-updates/ivdr-rules-examples"
        },
        {
          "text": "MDCG 2019-6 Rev5关于公告机构要求问答解析",
          "link": "/zh/insights/eu-mdr-updates/mdcg-2019-6-rev5"
        },
        {
          "text": "医疗器械法规 (MDR) 技术文档编写说明",
          "link": "/zh/insights/eu-mdr-updates/mdr-td-bpg"
        },
        {
          "text": "PMCF 问卷调查的伦理审查和知情同意",
          "link": "/zh/insights/eu-mdr-updates/pmcf-survey-ec-ic"
        },
        {
          "text": "Practical issues and examples",
          "link": "/zh/insights/eu-mdr-updates/practical-issues-and-examples"
        },
        {
          "text": "公告机构认证流程全解析：欧盟医疗器械合规的关键路径",
          "link": "/zh/insights/eu-mdr-updates/team-nb-mdr-certification-process"
        },
        {
          "text": "欧盟医疗器械技术审评机构发布 MDR 认证流程共识文件",
          "link": "/zh/insights/eu-mdr-updates/team-nb-position-paper-on-mdr-certification-process"
        }
      ]
    },
    {
      "text": "FDA 合规动态 (4)",
      "collapsed": true,
      "items": [
        {
          "text": "2025年伊始FDA密集发布指南文件",
          "link": "/zh/insights/fda-updates/2025-beginning-guidelines"
        },
        {
          "text": "FDA医疗器械网络安全指南解析：从合规走向卓越",
          "link": "/zh/insights/fda-updates/fda-cybersecurity-editors-note"
        },
        {
          "text": "解读FDA GUDID包装配置管理要求：医疗器械UDI合规的关键要素",
          "link": "/zh/insights/fda-updates/fda-guidance-gudid-2024"
        },
        {
          "text": "美国FDA对于重组胶原蛋白修复面膜类产品的分类与法规要求",
          "link": "/zh/insights/fda-updates/fda-recombinant-collagen-dressing"
        }
      ]
    },
    {
      "text": "法规解读分析 (26)",
      "collapsed": true,
      "items": [
        {
          "text": "网式雾化器设计技术参数",
          "link": "/zh/insights/analysis/网式雾化器设计技术参数"
        },
        {
          "text": "国家药监局关于发布34项医疗器械行业标准的公告（2024年第120号）",
          "link": "/zh/insights/analysis/2024-120"
        },
        {
          "text": "国家药监局关于发布36项医疗器械行业标准的公告（2024年第92号）",
          "link": "/zh/insights/analysis/2024-92"
        },
        {
          "text": "废止标准",
          "link": "/zh/insights/analysis/abolished-standards"
        },
        {
          "text": "医疗器械合规文件翻译助手使用指南",
          "link": "/zh/insights/analysis/ai-translator"
        },
        {
          "text": "洁净室合规性标准 ISO 14698 与 EN 17141 的选择困境",
          "link": "/zh/insights/analysis/clean-room-iso-14698-and-en-17141"
        },
        {
          "text": "中国药典2020年版与2025年版通则1105和1106实质性差异对比检查",
          "link": "/zh/insights/analysis/cp-2020-vs-2025-part4-general-1105-1106"
        },
        {
          "text": "网络安全生命周期",
          "link": "/zh/insights/analysis/cybersecurity-lifecycle"
        },
        {
          "text": "EU MDR下的UDI实施操作指南",
          "link": "/zh/insights/analysis/eu-mdr-udi"
        },
        {
          "text": "GB 9706.1-2020及配套并列标准、专用标准实施公告",
          "link": "/zh/insights/analysis/gb-9706-1-2020及配套并列标准、专用标准实施公告"
        },
        {
          "text": "GSPR 10.4.1与CMR",
          "link": "/zh/insights/analysis/gspr-10_4_1-and-cmr"
        },
        {
          "text": "香港医疗器械市场准入与监管合规：外国制造商战略指南",
          "link": "/zh/insights/analysis/hk-medical-device-regulatory-compliance"
        },
        {
          "text": "ISO 13485质量管理体系的深度解析与卓越实践",
          "link": "/zh/insights/analysis/iso-13485-qms-best-practice"
        },
        {
          "text": "有源医疗器械外部标记要求",
          "link": "/zh/insights/analysis/marking-requirements"
        },
        {
          "text": "关于医疗器械软件和GB/T 25000.51测试",
          "link": "/zh/insights/analysis/mdsw-gbt25000-51"
        },
        {
          "text": "标准发布",
          "link": "/zh/insights/analysis/new-standards"
        },
        {
          "text": "医疗器械产业本土化转型的助推剂：国家药监局2025年第30号公告深度解析",
          "link": "/zh/insights/analysis/nmpa-2025-30-notice"
        },
        {
          "text": "其他可能适用于医疗器械的法规和指令",
          "link": "/zh/insights/analysis/other-regulation-directive"
        },
        {
          "text": "构建智能化PDF文档翻译平台：从痛点到解决方案",
          "link": "/zh/insights/analysis/pdf-translation-tool"
        },
        {
          "text": "医疗器械中剩余风险的概念及其在风险管理和说明书编写中的意义",
          "link": "/zh/insights/analysis/residual-risk-and-information-in-ifu"
        },
        {
          "text": "现有技术水平(State-of-the-art)",
          "link": "/zh/insights/analysis/state-of-the-art"
        },
        {
          "text": "标准修改",
          "link": "/zh/insights/analysis/std-update"
        },
        {
          "text": "无菌和化学性能检验样品数量",
          "link": "/zh/insights/analysis/sterile-and-chemical-characteristics-testing"
        },
        {
          "text": "泰国医疗器械市场准入与监管合规：外国制造商战略指南",
          "link": "/zh/insights/analysis/thailand-medical-device-regulatory-compliance"
        },
        {
          "text": "医疗器械可用性工程注册审查指导原则的应用说明",
          "link": "/zh/insights/analysis/usability-explanation"
        },
        {
          "text": "如何撰写临床评价报告：IMDRF临床评价指南（2019）",
          "link": "/zh/insights/analysis/writing-cer"
        }
      ]
    },
    {
      "text": "临床评价方法论 (21)",
      "collapsed": true,
      "items": [
        {
          "text": "临床评价范围",
          "link": "/zh/insights/clinical-evaluation/临床评价范围"
        },
        {
          "text": "基准或类似产品",
          "link": "/zh/insights/clinical-evaluation/benchmark-and-similar-device"
        },
        {
          "text": "临床开发计划(CDP)",
          "link": "/zh/insights/clinical-evaluation/cdp"
        },
        {
          "text": "临床评价报告(CER)",
          "link": "/zh/insights/clinical-evaluation/cer"
        },
        {
          "text": "临床评价相关服务",
          "link": "/zh/insights/clinical-evaluation/clincial-evaluation-services"
        },
        {
          "text": "临床数据的分析",
          "link": "/zh/insights/clinical-evaluation/clinical-data-analysis"
        },
        {
          "text": "相关数据的评估与分析",
          "link": "/zh/insights/clinical-evaluation/data-appraisal-and-analysis"
        },
        {
          "text": "制造商产生的数据",
          "link": "/zh/insights/clinical-evaluation/data-generated-by-the-manufacturer"
        },
        {
          "text": "数据收集报告(DCR)",
          "link": "/zh/insights/clinical-evaluation/dcr"
        },
        {
          "text": "Endnote导入和导出",
          "link": "/zh/insights/clinical-evaluation/endnote-import-export"
        },
        {
          "text": "等同器械",
          "link": "/zh/insights/clinical-evaluation/equivalency"
        },
        {
          "text": "文献来源及选择理由",
          "link": "/zh/insights/clinical-evaluation/lit-database"
        },
        {
          "text": "文献评估标准",
          "link": "/zh/insights/clinical-evaluation/lit-review-standard"
        },
        {
          "text": "文献检索计划(LSP)",
          "link": "/zh/insights/clinical-evaluation/lsp"
        },
        {
          "text": "欧盟 MDCG 2025-9 指南解读：突破性医疗器械（BtX）",
          "link": "/zh/insights/clinical-evaluation/mdcg-2025-9"
        },
        {
          "text": "目标、输入和待评价产品信息",
          "link": "/zh/insights/clinical-evaluation/objective-input-due"
        },
        {
          "text": "风险管理",
          "link": "/zh/insights/clinical-evaluation/risk-management"
        },
        {
          "text": "文献选择标准",
          "link": "/zh/insights/clinical-evaluation/screening-criteria"
        },
        {
          "text": "文献选择过程",
          "link": "/zh/insights/clinical-evaluation/screening-process"
        },
        {
          "text": "检索方法",
          "link": "/zh/insights/clinical-evaluation/search-strategy"
        },
        {
          "text": "临床背景信息(SOTA)",
          "link": "/zh/insights/clinical-evaluation/sota"
        }
      ]
    }
  ]
}
